name: arm_pre_smoke

on:
  workflow_call:
    inputs:
      task_name:
        required: true
        type: string
      image_version:
        required: true
        type: string

jobs:
  JOB_pre_smoke:
    name: pre_smoke
    steps:
      -
        name: Checkout
        identifier: process_checkout
        uses: checkout
        with:
          ref: ${{ atomgit.event.pull_request.merge_commit_sha }}
          allow-unsafe-pr-checkout: true

      -
        name: download
        uses: obs-download
        with:
          endpoint: "https://obs.cn-north-4.myhuaweicloud.com"
          bucket: "ascend-ci"
          access-key: ${{ secrets.AK }}
          secret-key: ${{ secrets.SK }}
          key: |
            ${{ env.obs_path }}/pr_filelist.txt
            ${{ env.obs_path }}/pr_filelist_mod.txt
            ${{ env.obs_path }}/pre_smoke.sh
          path: ${{ steps.process_checkout.outputs.path }}

      -
        name: pre_smoke
        timeout-minutes: 120
        run: |
          set -e
          # set env
          whoami
          bash ${{ steps.process_checkout.outputs.path }}/pre_smoke.sh

    if: "${{ default() }}"
    runs-on: ['self-hosted','npu=1','smoke=204']
    container:
          image: swr.cn-north-4.myhuaweicloud.com/hw-ascend/${{ inputs.image_version }}
