name: llt_action

on:
  workflow_call:
    inputs:
      image_version:
        required: true
        type: string

jobs:
  JOB_ut:
    name: ut
    steps:
      -
        name: Checkout
        identifier: process_checkout
        uses: checkout
        with:
          ref: ${{ atomgit.event.pull_request.merge_commit_sha || atomgit.sha }}
          allow-unsafe-pr-checkout: true

      -
        name: download
        uses: obs-download
        with:
          endpoint: "https://obs.cn-north-4.myhuaweicloud.com"
          bucket: "ascend-ci"
          access-key: ${{ secrets.AK }}
          secret-key: ${{ secrets.SK }}
          key: |
            ${{ env.obs_path }}/pr_filelist.txt
            ${{ env.obs_path }}/pr_filelist_mod.txt
            ${{ env.obs_path }}/ut.sh
          path: ${{ steps.process_checkout.outputs.path }}

      -
        name: ut
        timeout-minutes: 120
        run: |
          set -e
          # set env
          bash ${{ steps.process_checkout.outputs.path }}/ut.sh

    if: "${{ default() }}"
    runs-on: [ 'self-hosted','npu=1','smoke=201' ]
    container:
        image: swr.cn-north-4.myhuaweicloud.com/hw-ascend/${{ inputs.image_version }}
